/* =========================================================================
   ESG - equipment & spare-parts catalog (car-wash hardware)

   Appends a third top-level category ("equipment") with five subcategories,
   then pushes every hardware item into the shared ESG_PRODUCTS array.

   Equipment schema (no liters / dilution / eco):
     slug, cat:"equipment", sub:<subId>, name/blurb={ka,en},
     spec={ka,en} (optional short origin/power/size line),
     code:"" (article code, blank if unknown),
     img:"assets/catalog/eq-*.webp"
   ========================================================================= */
(function () {
  "use strict";

  /* ---- register the category + subcategories ---- */
  window.ESG_CATEGORIES = (window.ESG_CATEGORIES || []).concat([{
    id: "equipment",
    name: { ka: "აღჭურვილობა და ნაწილები", en: "Equipment & Parts" },
    subs: [
      { id: "panels",  name: { ka: "მართვის პანელები",        en: "Control Panels" } },
      { id: "motors",  name: { ka: "ძრავები და ტუმბოები",      en: "Motors & Pumps" } },
      { id: "vacuums", name: { ka: "მტვერსასრუტები და ნაწილები", en: "Vacuums & Parts" } },
      { id: "kits",    name: { ka: "სარემონტო კომპლექტები",    en: "Repair Kits" } },
      { id: "spare",   name: { ka: "სათადარიგო ნაწილები",      en: "Spare Parts" } }
    ]
  }]);

  function eq(sub, slug, ka, en, code, blurbKa, blurbEn, specKa, specEn, img) {
    var p = {
      slug: slug, cat: "equipment", sub: sub,
      name: { ka: ka, en: en }, code: code || "",
      img: img
    };
    if (blurbKa) p.blurb = { ka: blurbKa, en: blurbEn };
    if (specKa)  p.spec  = { ka: specKa,  en: specEn };
    return p;
  }

  var IMG = "assets/catalog/";

  var EQUIPMENT = [
    /* ---------------- CONTROL PANELS ---------------- */
    eq("panels", "eq-panel-3func", "3-ფუნქციანი მართვის პანელი", "3-Function Control Panel", "62945",
      "სამრეჟიმიანი მართვის პანელი თვითმომსახურების ბოქსისთვის.", "Three-mode control panel for a self-service bay.",
      "წყალი · ქაფი · ცვილი", "Water · Foam · Wax", IMG + "eq-pan-1.webp"),
    eq("panels", "eq-panel-4func-steel", "4-ფუნქციანი ლითონის მართვის პანელი", "4-Function Stainless Panel", "62946",
      "ოთხრეჟიმიანი უჟანგავი ფოლადის მართვის პანელი.", "Four-mode stainless-steel control panel.",
      "უჟანგავი ფოლადი · 4 რეჟიმი", "Stainless steel · 4 modes", IMG + "eq-pan-2.webp"),
    eq("panels", "eq-panel-4func", "4-ფუნქციანი მართვის პანელი", "4-Function Control Panel", "",
      "ოთხრეჟიმიანი მართვის პანელი თვითმომსახურების ბოქსისთვის.", "Four-mode control panel for a self-service bay.",
      "", "", IMG + "eq-pan-3.webp"),
    eq("panels", "eq-panel-led", "LED მართვის პანელი", "LED Control Panel", "",
      "LED-განათებიანი მართვის პანელი მკაფიო რეჟიმის ინდიკაციით.", "LED-lit control panel with clear mode indication.",
      "", "", IMG + "eq-pan-4.webp"),
    eq("panels", "eq-panel-multi", "მრავალფუნქციანი მართვის პანელი", "Multifunction Control Panel", "",
      "სრული ციკლის მართვის პანელი ცხელი წყლისა და ოსმოსის რეჟიმებით.", "Full-cycle control panel with hot-water and osmosis modes.",
      "წყალი · ცხელი წყალი · ქაფი · ცვილი · ოსმოსი", "Water · Hot water · Foam · Wax · Osmosis", IMG + "eq-pan-5.webp"),
    eq("panels", "eq-panel-basic", "მართვის პანელი", "Control Panel", "",
      "საბაზისო მართვის პანელი თვითმომსახურების ბოქსისთვის.", "Basic control panel for a self-service bay.",
      "", "", IMG + "eq-pan-6.webp"),
    eq("panels", "eq-panel-vacuum", "მტვერსასრუტების მართვის პანელი", "Vacuum Control Panel", "62497",
      "მართვის პანელი თვითმომსახურების მტვერსასრუტებისთვის.", "Control panel for self-service vacuum stations.",
      "", "", IMG + "eq-pan-7.webp"),
    eq("panels", "eq-panel-vacuum-tyre", "მტვერსასრუტის მართვის პანელი - საბურავის წნევის ფუნქციით", "Vacuum Panel with Tyre Inflation", "62498",
      "მტვერსასრუტის პანელი ჩაშენებული საბურავის წნევის დაყენების ფუნქციით.", "Vacuum panel with built-in tyre-inflation function.",
      "მტვერსასრუტი + საბურავის წნევა", "Vacuum + tyre inflation", IMG + "eq-pan-8.webp"),
    eq("panels", "eq-panel-dispenser-iron", "საბურავისა და პლასტიკის გასაშავებელი დისპენსერი - რკინა", "Tyre & Plastic Dressing Dispenser - Iron", "64406",
      "თერმოშეღებილი რკინის დისპენსერი საბურავისა და პლასტიკის გასაშავებლად.", "Thermo-painted iron dispenser for tyre and plastic dressing.",
      "თერმოშეღებილი რკინა", "Thermo-painted iron", IMG + "eq-pan-9.webp"),
    eq("panels", "eq-panel-dispenser-steel", "საბურავისა და პლასტიკის დისპენსერი - უჟანგავი", "Tyre & Plastic Dressing Dispenser - Stainless", "64402",
      "უჟანგავი ლითონის დისპენსერი საბურავისა და პლასტიკის გასაშავებლად.", "Stainless-steel dispenser for tyre and plastic dressing.",
      "უჟანგავი ლითონი", "Stainless steel", IMG + "eq-pan-10.webp"),
    eq("panels", "eq-coin-changer", "ხურდის დამშლელი", "Coin Changer", "",
      "ბანკნოტის ხურდად დამშლელი აპარატი თვითმომსახურებისთვის.", "Banknote-to-coin changer for self-service stations.",
      "", "", IMG + "eq-pan-11.webp"),
    eq("panels", "eq-coin-acceptor", "ხურდის მიმღები", "Coin Acceptor", "62528",
      "მონეტის მიმღები მოდული მართვის პანელისთვის.", "Coin-acceptor module for the control panel.",
      "", "", IMG + "eq-pan-12.webp"),

    /* ---------------- MOTORS & PUMPS ---------------- */
    eq("motors", "eq-motor-11kw", "ელექტრო 3-ფაზიანი ძრავი 11 kW", "3-Phase Electric Motor 11 kW", "65027",
      "სამფაზიანი ელექტრო ძრავი მაღალი წარმადობის ტუმბოსთვის.", "Three-phase electric motor for a high-output pump.",
      "11 kW · 50 Hz · 1455 rpm", "11 kW · 50 Hz · 1455 rpm", IMG + "eq-mot-1.webp"),
    eq("motors", "eq-motor-4kw", "ელექტრო 3-ფაზიანი ძრავი 4 kW", "3-Phase Electric Motor 4 kW", "65024",
      "სამფაზიანი ელექტრო ძრავი ტუმბოსთვის.", "Three-phase electric motor for a pump.",
      "4 kW · 50 Hz · 1455 rpm", "4 kW · 50 Hz · 1455 rpm", IMG + "eq-mot-2.webp"),
    eq("motors", "eq-motor-55kw", "ელექტრო 3-ფაზიანი ძრავი 5,5 kW", "3-Phase Electric Motor 5.5 kW", "64362",
      "სამფაზიანი ელექტრო ძრავი ტუმბოსთვის.", "Three-phase electric motor for a pump.",
      "5.5 kW · 50 Hz · 1455 rpm", "5.5 kW · 50 Hz · 1455 rpm", IMG + "eq-mot-3.webp"),
    eq("motors", "eq-motor-75kw", "ელექტრო 3-ფაზიანი ძრავი 7,5 kW", "3-Phase Electric Motor 7.5 kW", "65025",
      "სამფაზიანი ელექტრო ძრავი ტუმბოსთვის.", "Three-phase electric motor for a pump.",
      "7.5 kW · 50 Hz · 1455 rpm", "7.5 kW · 50 Hz · 1455 rpm", IMG + "eq-mot-4.webp"),
    eq("motors", "eq-motor-92kw", "ელექტრო 3-ფაზიანი ძრავი 9,2 kW", "3-Phase Electric Motor 9.2 kW", "65026",
      "სამფაზიანი ელექტრო ძრავი მაღალი წარმადობის ტუმბოსთვის.", "Three-phase electric motor for a high-output pump.",
      "9.2 kW · 50 Hz · 1455 rpm", "9.2 kW · 50 Hz · 1455 rpm", IMG + "eq-mot-5.webp"),
    eq("motors", "eq-motor-mazzoni-coupling", "Mazzoni ელექტრო 3-ფაზიანი ძრავი მუფტით 5,5 kW", "Mazzoni 3-Phase Motor with Coupling 5.5 kW", "62384",
      "Mazzoni-ის სამფაზიანი ძრავი მუფტით, წყლის ტუმბოსთვის.", "Mazzoni three-phase motor with coupling, for a water pump.",
      "იტალია · 5.5 kW", "Italy · 5.5 kW", IMG + "eq-mot-6.webp"),
    eq("motors", "eq-pump-mazzoni-brass", "Mazzoni ლატუნის წყლის ტუმბო", "Mazzoni Brass Water Pump", "62629",
      "Mazzoni-ის ლატუნის თავიანი მაღალი წნევის წყლის ტუმბო.", "Mazzoni brass-head high-pressure water pump.",
      "იტალია · 7.62–8.72 kW · 1420–1740 rpm", "Italy · 7.62–8.72 kW · 1420–1740 rpm", IMG + "eq-mot-7.webp"),
    eq("motors", "eq-pump-mazzoni-nickel", "Mazzoni ნიკელის წყლის ტუმბო", "Mazzoni Nickel Water Pump", "62630",
      "Mazzoni-ის ნიკელის თავიანი მაღალი წნევის წყლის ტუმბო.", "Mazzoni nickel-head high-pressure water pump.",
      "იტალია · 7.62–8.72 kW · 1420–1740 rpm", "Italy · 7.62–8.72 kW · 1420–1740 rpm", IMG + "eq-mot-8.webp"),
    eq("motors", "eq-motor-nicolini-55kw", "Nicolini ელექტრო 3-ფაზიანი ძრავი 5,5 kW", "Nicolini 3-Phase Motor 5.5 kW", "63051",
      "Nicolini-ის სამფაზიანი ელექტრო ძრავი ტუმბოსთვის.", "Nicolini three-phase electric motor for a pump.",
      "იტალია · 5.5 kW · 1750 rpm", "Italy · 5.5 kW · 1750 rpm", IMG + "eq-mot-9.webp"),
    eq("motors", "eq-pump-hawk-200bar", "Hawk წყლის ტუმბო 200 bar", "Hawk Water Pump 200 bar", "00268",
      "Hawk-ის მაღალი წნევის წყლის ტუმბო თვითმომსახურების სისტემისთვის.", "Hawk high-pressure water pump for self-service systems.",
      "200 bar · 11 L/წთ · 5.7–6.4 kW", "200 bar · 11 L/min · 5.7–6.4 kW", IMG + "eq-mot-10.webp"),

    /* ---------------- VACUUMS & PARTS ---------------- */
    eq("vacuums", "eq-vac-handle-300", "300 მმ მტვერსასრუტის სახელური - ჰაერის რეგულატორით", "300 mm Vacuum Handle with Air Regulator", "00364",
      "ალუმინის სახელური ჰაერის ნაკადის რეგულატორით, 32 მმ შემერთებით.", "Aluminium handle with airflow regulator and 32 mm connection.",
      "300 მმ · 32 მმ", "300 mm · 32 mm", IMG + "eq-vac-1.webp"),
    eq("vacuums", "eq-vac-nozzle-140", "მტვერსასრუტის ცხვირი 140 მმ", "Vacuum Nozzle 140 mm", "00358",
      "მტვერსასრუტის ცხვირი 32 მმ შემერთებით.", "Vacuum nozzle with 32 mm connection.",
      "140 მმ · 32 მმ", "140 mm · 32 mm", IMG + "eq-vac-2.webp"),
    eq("vacuums", "eq-vac-rl118a-30l", "RL118A-30L პროფესიონალური 1-ძრავიანი მტვერსასრუტი", "RL118A-30L Professional Single-Motor Vacuum", "64023",
      "30 ლიტრიანი უჟანგავი ავზიანი ერთძრავიანი პროფესიონალური მტვერსასრუტი.", "30 L stainless-tank single-motor professional vacuum.",
      "30 ლ · 1000 W", "30 L · 1000 W", IMG + "eq-vac-3.webp"),
    eq("vacuums", "eq-vac-wl70-2b", "WL70-70L2B პროფესიონალური 2-ძრავიანი მტვერსასრუტი", "WL70-70L2B Professional Twin-Motor Vacuum", "64022",
      "70 ლიტრიანი უჟანგავი ავზიანი ორძრავიანი პროფესიონალური მტვერსასრუტი.", "70 L stainless-tank twin-motor professional vacuum.",
      "70 ლ · 2×1000 W", "70 L · 2×1000 W", IMG + "eq-vac-4.webp"),
    eq("vacuums", "eq-vac-wl70-3b", "WL70-70L3B პროფესიონალური 3-ძრავიანი მტვერსასრუტი", "WL70-70L3B Professional Triple-Motor Vacuum", "64401",
      "70 ლიტრიანი უჟანგავი ავზიანი სამძრავიანი პროფესიონალური მტვერსასრუტი.", "70 L stainless-tank triple-motor professional vacuum.",
      "70 ლ · 3×1000 W", "70 L · 3×1000 W", IMG + "eq-vac-5.webp"),
    eq("vacuums", "eq-vac-hose-32-cn", "მტვერსასრუტის შლანგი 32 მმ", "Vacuum Hose 32 mm", "00340",
      "მტვერსასრუტის შლანგი, 32 მმ.", "Vacuum hose, 32 mm.",
      "32 მმ · ჩინეთი", "32 mm · China", IMG + "eq-vac-6.webp"),
    eq("vacuums", "eq-vac-hose-38-de", "მტვერსასრუტის შლანგი 38 მმ", "Vacuum Hose 38 mm", "61464",
      "მტვერსასრუტის შლანგი, 38 მმ.", "Vacuum hose, 38 mm.",
      "38 მმ · გერმანია", "38 mm · Germany", IMG + "eq-vac-7.webp"),
    eq("vacuums", "eq-vac-hose-38-cn", "მტვერსასრუტის შლანგი 38 მმ", "Vacuum Hose 38 mm", "61982",
      "მტვერსასრუტის შლანგი, 38 მმ.", "Vacuum hose, 38 mm.",
      "38 მმ · ჩინეთი", "38 mm · China", IMG + "eq-vac-8.webp"),
    eq("vacuums", "eq-vac-filter-wl70", "მტვერსასრუტის ფილტრი WL70", "Vacuum Filter WL70", "00362",
      "WL70 სერიის მტვერსასრუტის სათადარიგო ფილტრი.", "Replacement filter for the WL70-series vacuum.",
      "", "", IMG + "eq-vac-9.webp"),
    eq("vacuums", "eq-vac-motor-1000", "მტვერსასრუტის ძრავი AD30MOTOR 1000 W", "Vacuum Motor AD30MOTOR 1000 W", "60327",
      "სათადარიგო ძრავი მტვერსასრუტისთვის.", "Replacement motor for a vacuum unit.",
      "1000 W · 220 V", "1000 W · 220 V", IMG + "eq-vac-10.webp"),
    eq("vacuums", "eq-vac-motor-1200", "მტვერსასრუტის ძრავი AD30MOTOR 1200 W", "Vacuum Motor AD30MOTOR 1200 W", "62473",
      "სათადარიგო ძრავი მტვერსასრუტისთვის.", "Replacement motor for a vacuum unit.",
      "1200 W · 220 V", "1200 W · 220 V", IMG + "eq-vac-11.webp"),
    eq("vacuums", "eq-vac-filter-30l", "მტვერსასრუტის ფილტრი 30 L", "Vacuum Filter 30 L", "64814",
      "სათადარიგო ფილტრი 30 ლიტრიანი მტვერსასრუტისთვის.", "Replacement filter for a 30 L vacuum.",
      "30 ლ", "30 L", IMG + "eq-vac-12.webp"),
    eq("vacuums", "eq-vac-nozzle-250", "მტვერსასრუტის ცხვირი 250 მმ", "Vacuum Nozzle 250 mm", "00359",
      "მტვერსასრუტის ცხვირი 38 მმ შემერთებით.", "Vacuum nozzle with 38 mm connection.",
      "250 მმ · 38 მმ · ჩინეთი", "250 mm · 38 mm · China", IMG + "eq-vac-13.webp"),

    /* ---------------- REPAIR KITS ---------------- */
    eq("kits", "eq-kit-bypass-spring-hawk", "ბაიპასის ზამბარა HAWK", "Bypass Spring HAWK", "00295",
      "სათადარიგო ზამბარა HAWK-ის ბაიპასისთვის.", "Replacement spring for the HAWK bypass.",
      "HAWK", "HAWK", IMG + "eq-kit-1.webp"),
    eq("kits", "eq-kit-bypass-spring-kit-hawk", "ბაიპასის სარემონტო კომპლექტი ზამბარით HAWK", "Bypass Repair Kit with Spring HAWK", "00288",
      "ბაიპასის სრული სარემონტო კომპლექტი ზამბარით, HAWK.", "Complete bypass repair kit with spring, HAWK.",
      "HAWK", "HAWK", IMG + "eq-kit-2.webp"),
    eq("kits", "eq-kit-bypass-seals-hawk", "ბაიპასის ჩობალის (სალნიკები) სარემონტო კომპლექტი HAWK", "Bypass Seals Repair Kit HAWK", "00286",
      "ბაიპასის სალნიკების სარემონტო კომპლექტი, HAWK.", "Bypass seal repair kit, HAWK.",
      "HAWK", "HAWK", IMG + "eq-kit-3.webp"),
    eq("kits", "eq-kit-dispenser", "დოზატორის სარემონტო კომპლექტი", "Dispenser Repair Kit", "61275",
      "სარემონტო კომპლექტი ქაფის/ცვილის დოზატორისთვის.", "Repair kit for the foam/wax dispenser.",
      "", "", IMG + "eq-kit-4.webp"),
    eq("kits", "eq-kit-mazzoni-bypass", "Mazzoni ბაიპასის სარემონტო კომპლექტი", "Mazzoni Bypass Repair Kit", "62378",
      "Mazzoni-ის ბაიპასის სარემონტო კომპლექტი.", "Mazzoni bypass repair kit.",
      "იტალია", "Italy", IMG + "eq-kit-5.webp"),
    eq("kits", "eq-kit-mazzoni-pump", "Mazzoni წყლის ტუმბოს სარემონტო კომპლექტი", "Mazzoni Water Pump Repair Kit", "62381",
      "Mazzoni-ის წყლის ტუმბოს სარემონტო კომპლექტი.", "Mazzoni water-pump repair kit.",
      "იტალია", "Italy", IMG + "eq-kit-6.webp"),
    eq("kits", "eq-kit-mazzoni-valves", "Mazzoni წყლის ტუმბოს სარქველები", "Mazzoni Water Pump Valves", "62379",
      "სათადარიგო სარქველები Mazzoni-ის წყლის ტუმბოსთვის.", "Replacement valves for the Mazzoni water pump.",
      "იტალია", "Italy", IMG + "eq-kit-7.webp"),
    eq("kits", "eq-kit-mazzoni-bolt", "Mazzoni წყლის ტუმბოს ბოლტი", "Mazzoni Water Pump Bolt", "62627",
      "სათადარიგო ბოლტი Mazzoni-ის წყლის ტუმბოსთვის.", "Replacement bolt for the Mazzoni water pump.",
      "იტალია", "Italy", IMG + "eq-kit-8.webp"),
    eq("kits", "eq-kit-mazzoni-oil-seals", "Mazzoni წყლის ტუმბოს ზეთის სალნიკები", "Mazzoni Water Pump Oil Seals", "62380",
      "სათადარიგო ზეთის სალნიკები Mazzoni-ის წყლის ტუმბოსთვის.", "Replacement oil seals for the Mazzoni water pump.",
      "იტალია", "Italy", IMG + "eq-kit-9.webp"),
    eq("kits", "eq-kit-mazzoni-rod", "Mazzoni წყლის ტუმბოს შატუნი", "Mazzoni Water Pump Connecting Rod", "62383",
      "სათადარიგო შატუნი Mazzoni-ის წყლის ტუმბოსთვის.", "Replacement connecting rod for the Mazzoni water pump.",
      "იტალია", "Italy", IMG + "eq-kit-10.webp"),
    eq("kits", "eq-kit-pump-oil-seals-hawk", "წყლის ტუმბოს ზეთის ჩობალი (სალნიკები) HAWK", "Water Pump Oil Seals HAWK", "00275",
      "წყლის ტუმბოს ზეთის სალნიკები, HAWK.", "Water-pump oil seals, HAWK.",
      "HAWK", "HAWK", IMG + "eq-kit-11.webp"),
    eq("kits", "eq-kit-pump-repair-hawk", "წყლის ტუმბოს სარემონტო კომპლექტი HAWK", "Water Pump Repair Kit HAWK", "00272",
      "წყლის ტუმბოს სრული სარემონტო კომპლექტი, HAWK.", "Complete water-pump repair kit, HAWK.",
      "HAWK", "HAWK", IMG + "eq-kit-12.webp"),
    eq("kits", "eq-kit-pump-valves-hawk", "წყლის ტუმბოს სარქველები HAWK", "Water Pump Valves HAWK", "00306",
      "სათადარიგო სარქველები წყლის ტუმბოსთვის, HAWK.", "Replacement valves for the water pump, HAWK.",
      "HAWK", "HAWK", IMG + "eq-kit-13.webp"),
    eq("kits", "eq-kit-pump-ceramic-hawk", "წყლის ტუმბოს ფაიფური HAWK", "Water Pump Ceramic Pistons HAWK", "00274",
      "ფაიფურის (კერამიკის) დგუშები წყლის ტუმბოსთვის, HAWK.", "Ceramic pistons for the water pump, HAWK.",
      "HAWK", "HAWK", IMG + "eq-kit-14.webp"),
    eq("kits", "eq-kit-hawk-bypass-valve", "Hawk ბაიპასის სარქველი", "Hawk Bypass Valve", "00287",
      "სათადარიგო სარქველი HAWK-ის ბაიპასისთვის.", "Replacement valve for the HAWK bypass.",
      "HAWK", "HAWK", IMG + "eq-kit-15.webp"),
    eq("kits", "eq-kit-hawk-bypass-spring-kit", "Hawk ზამბარიანი ბაიპასის სარემონტო კომპლექტი", "Hawk Bypass Repair Kit with Spring", "00294",
      "ბაიპასის სარემონტო კომპლექტი ზამბარით, HAWK.", "Bypass repair kit with spring, HAWK.",
      "HAWK", "HAWK", IMG + "eq-kit-16.webp"),
    eq("kits", "eq-kit-hawk-pump-bolt", "Hawk წყლის ტუმბოს ბოლტი", "Hawk Water Pump Bolt", "00283",
      "სათადარიგო ბოლტი HAWK-ის წყლის ტუმბოსთვის.", "Replacement bolt for the HAWK water pump.",
      "HAWK", "HAWK", IMG + "eq-kit-17.webp"),
    eq("kits", "eq-kit-hawk-pump-brass-kit", "Hawk წყლის ტუმბოს ლატუნის სარემონტო კომპლექტი", "Hawk Water Pump Brass Repair Kit", "00273",
      "ლატუნის სარემონტო კომპლექტი HAWK-ის წყლის ტუმბოსთვის.", "Brass repair kit for the HAWK water pump.",
      "HAWK", "HAWK", IMG + "eq-kit-18.webp"),
    eq("kits", "eq-kit-hawk-pump-seal", "Hawk წყლის ტუმბოს სალნიკი", "Hawk Water Pump Seal", "00278",
      "სათადარიგო სალნიკი HAWK-ის წყლის ტუმბოსთვის.", "Replacement seal for the HAWK water pump.",
      "HAWK", "HAWK", IMG + "eq-kit-19.webp"),

    /* ---------------- SPARE PARTS ---------------- */
    eq("spare", "eq-spr-fitting-6", "შტუცერი 6 მმ", "Fitting 6 mm", "64473",
      "სათადარიგო შტუცერი, 6 მმ.", "Replacement fitting, 6 mm.", "6 მმ · გერმანია", "6 mm · Germany", IMG + "eq-spr-1.webp"),
    eq("spare", "eq-spr-fitting-8", "შტუცერი 8 მმ", "Fitting 8 mm", "64474",
      "სათადარიგო შტუცერი, 8 მმ.", "Replacement fitting, 8 mm.", "8 მმ · გერმანია", "8 mm · Germany", IMG + "eq-spr-2.webp"),
    eq("spare", "eq-spr-auto-dispenser", "ავტომატური ქაფისა და ცვილის დოზატორი", "Automatic Foam & Wax Dispenser", "",
      "ავტომატური დოზატორი ქაფისა და ცვილისთვის.", "Automatic dispenser for foam and wax.", "იტალია", "Italy", IMG + "eq-spr-3.webp"),
    eq("spare", "eq-spr-karcher-adapter", "გადასაბმელი კერხერის თავით M22M", "Karcher-Head Coupling M22M", "A11PS-M22MM22M",
      "გადასაბმელი Karcher-ის ტიპის M22 თავით.", "Coupling with Karcher-type M22 head.", "M22M", "M22M", IMG + "eq-spr-4.webp"),
    eq("spare", "eq-spr-ball-coupling", "გარე ბურთულა ქურო (ვინჩესტერი) WAP KEW", "Ball Coupling (Winchester) WAP KEW", "00316",
      "გარე ბურთულა ქურო WAP / KEW აპარატებისთვის.", "External ball coupling for WAP / KEW units.", "R+M · გერმანია", "R+M · Germany", IMG + "eq-spr-5.webp"),
    eq("spare", "eq-spr-lp-valve-10", "დაბალი წნევის ელექტრო სარქველი 10 bar", "Low-Pressure Electric Valve 10 bar", "61498",
      "დაბალი წნევის ელექტრო სარქველი.", "Low-pressure electric (solenoid) valve.", "10 bar", "10 bar", IMG + "eq-spr-6.webp"),
    eq("spare", "eq-spr-hawk-bypass", "ელექტრო ჰავკის წნევის მარეგულირებელი (ბაიპასი)", "Hawk Electric Pressure Regulator (Bypass)", "60484",
      "ელექტრო წნევის მარეგულირებელი HAWK-ის ტუმბოსთვის.", "Electric pressure regulator for the HAWK pump.", "HAWK", "HAWK", IMG + "eq-spr-7.webp"),
    eq("spare", "eq-spr-winter-valve", "ზამთრის რეჟიმის ვინტილი ST-2300", "Winter-Mode Valve ST-2300", "00493",
      "ზამთრის რეჟიმის მაღალი წნევის გამშვები ვინტილი (პისტოლეტი).", "Winter-mode high-pressure trigger valve (gun).", "ST-2300 · გერმანია", "ST-2300 · Germany", IMG + "eq-spr-8.webp"),
    eq("spare", "eq-spr-sewer-nozzle", "კანალიზაციის ფრქვევანა", "Sewer Nozzle", "N1001",
      "ფრქვევანა კანალიზაციის გაწმენდისთვის.", "Nozzle for sewer cleaning.", "", "", IMG + "eq-spr-9.webp"),
    eq("spare", "eq-spr-lance-head-rb", "ლულის თავი - წითელი/ლურჯი", "Lance Head - Red/Blue", "NH02",
      "ლულის სათადარიგო თავი, წითელი/ლურჯი.", "Replacement lance head, red/blue.", "", "", IMG + "eq-spr-10.webp"),
    eq("spare", "eq-spr-lance-head", "ლულის თავი", "Lance Head", "NH0601",
      "ლულის სათადარიგო თავი.", "Replacement lance head.", "", "", IMG + "eq-spr-11.webp"),
    eq("spare", "eq-spr-swivel-90-de", "მაბრუნი გადაბმა 90°", "Swivel Coupling 90°", "61462",
      "მაბრუნი 90° გადაბმა შლანგისთვის.", "90° swivel coupling for the hose.", "გერმანია · TA06-K01", "Germany · TA06-K01", IMG + "eq-spr-12.webp"),
    eq("spare", "eq-spr-swivel-90", "მაბრუნი გადაბმა 90°", "Swivel Coupling 90°", "",
      "მაბრუნი 90° გადაბმა შლანგისთვის.", "90° swivel coupling for the hose.", "", "", IMG + "eq-spr-13.webp"),
    eq("spare", "eq-spr-adapter-14-14", "მაერთებელი გადამყვანი 1/4–1/4", "Adapter 1/4–1/4", "61457",
      "მაერთებელი გადამყვანი, 1/4–1/4.", "Connector adapter, 1/4–1/4.", "", "", IMG + "eq-spr-14.webp"),
    eq("spare", "eq-spr-adapter-small", "მაერთებელი გადამყვანი - პატარა", "Adapter - Small", "00314",
      "მცირე ზომის მაერთებელი გადამყვანი.", "Small-size connector adapter.", "", "", IMG + "eq-spr-15.webp"),
    eq("spare", "eq-spr-adapter", "მაერთებელი გადამყვანი", "Adapter", "61458",
      "მაერთებელი გადამყვანი, 3/8–3/8.", "Connector adapter, 3/8–3/8.", "", "", IMG + "eq-spr-16.webp"),
    eq("spare", "eq-spr-mazzoni-elec-bypass", "Mazzoni ელექტრო წნევის მარეგულირებელი (ბაიპასი)", "Mazzoni Electric Pressure Regulator (Bypass)", "62385",
      "Mazzoni-ის ელექტრო წნევის მარეგულირებელი.", "Mazzoni electric pressure regulator.", "იტალია", "Italy", IMG + "eq-spr-17.webp"),
    eq("spare", "eq-spr-mazzoni-mech-bypass", "Mazzoni მექანიკური წნევის მარეგულირებელი (ბაიპასი)", "Mazzoni Mechanical Pressure Regulator (Bypass)", "62386",
      "Mazzoni-ის მექანიკური წნევის მარეგულირებელი.", "Mazzoni mechanical pressure regulator.", "იტალია", "Italy", IMG + "eq-spr-18.webp"),
    eq("spare", "eq-spr-manometer-400", "მანომეტრი 400 BAR", "Manometer 400 BAR", "PG04",
      "წნევის მანომეტრი, 400 bar.", "Pressure manometer, 400 bar.", "400 bar", "400 bar", IMG + "eq-spr-19.webp"),
    eq("spare", "eq-spr-manometer-de", "მანომეტრი", "Manometer", "",
      "წნევის მანომეტრი.", "Pressure manometer.", "გერმანია", "Germany", IMG + "eq-spr-20.webp"),
    eq("spare", "eq-spr-relief-valve", "მარეგულირებელი ვინტილი ST-2300", "Pressure-Relief Valve ST-2300", "64840",
      "მაღალი წნევის გამშვები მარეგულირებელი ვინტილი (პისტოლეტი).", "High-pressure relief trigger valve (gun).", "ST-2300 · გერმანია", "ST-2300 · Germany", IMG + "eq-spr-21.webp"),
    eq("spare", "eq-spr-hp-valve-250", "მაღალი წნევის სარქველი 250 bar", "High-Pressure Valve 250 bar", "",
      "მაღალი წნევის სარქველი, 250 bar.", "High-pressure valve, 250 bar.", "250 bar", "250 bar", IMG + "eq-spr-22.webp"),
    eq("spare", "eq-spr-hawk-mech-bypass", "მექანიკური ჰავკის წნევის მარეგულირებელი (ბაიპასი)", "Hawk Mechanical Pressure Regulator (Bypass)", "64204",
      "მექანიკური წნევის მარეგულირებელი HAWK-ის ტუმბოსთვის.", "Mechanical pressure regulator for the HAWK pump.", "HAWK", "HAWK", IMG + "eq-spr-23.webp"),
    eq("spare", "eq-spr-sleeve-6", "მომჭიმი ქურო (გილზა) 6 მმ", "Compression Sleeve 6 mm", "00323",
      "მომჭიმი ქურო (გილზა), 6 მმ.", "Compression sleeve, 6 mm.", "6 მმ · გერმანია", "6 mm · Germany", IMG + "eq-spr-24.webp"),
    eq("spare", "eq-spr-sleeve-8", "მომჭიმი ქურო (გილზა) 8 მმ", "Compression Sleeve 8 mm", "62492",
      "მომჭიმი ქურო (გილზა), 8 მმ.", "Compression sleeve, 8 mm.", "8 მმ · გერმანია", "8 mm · Germany", IMG + "eq-spr-25.webp"),
    eq("spare", "eq-spr-pantograph-bearing", "პანტოგრაფის საკისარი", "Pantograph Bearing", "TA06-K02",
      "სათადარიგო საკისარი პანტოგრაფისთვის.", "Replacement bearing for the pantograph.", "", "", IMG + "eq-spr-26.webp"),
    eq("spare", "eq-spr-straight-180", "პირდაპირი გადაბმა 180°", "Straight Coupling 180°", "A25SS-38F38M",
      "პირდაპირი 180° გადაბმა შლანგისთვის.", "180° straight coupling for the hose.", "", "", IMG + "eq-spr-27.webp"),
    eq("spare", "eq-spr-pistol-insert", "პისტოლეტის ლითნის ფოლადის ჩასადები", "Pistol Brass-Steel Insert", "62438",
      "ლითნის/ფოლადის ჩასადები პისტოლეტისთვის.", "Brass-steel insert for the trigger gun.", "", "", IMG + "eq-spr-28.webp"),
    eq("spare", "eq-spr-locks", "საკეტები", "Locks", "62053",
      "სათადარიგო საკეტები.", "Replacement locks.", "", "", IMG + "eq-spr-29.webp"),
    eq("spare", "eq-spr-solenoid-dispenser", "სოლენოიდის დოზატორი ქაფისა და ცვილისთვის", "Solenoid Dispenser for Foam & Wax", "",
      "სოლენოიდიანი დოზატორი (ტუმბო) ქაფისა და ცვილისთვის.", "Solenoid dispenser (pump) for foam and wax.", "", "", IMG + "eq-spr-30.webp"),
    eq("spare", "eq-spr-tornado", "ტორნადო რკინის ღერძით", "Tornado with Iron Shaft", "T0202",
      "ტორნადო ფრქვევანა რკინის ღერძით.", "Tornado nozzle with iron shaft.", "", "", IMG + "eq-spr-31.webp"),
    eq("spare", "eq-spr-check-valve", "უკანა სარქველი", "Check Valve", "62054",
      "უკუსვლის (უკანა) სარქველი.", "Non-return (check) valve.", "გერმანია", "Germany", IMG + "eq-spr-32.webp"),
    eq("spare", "eq-spr-console-fixed", "უჟანგავი ლითონის მოძრავი კონსოლი (პანტოგრაფი)", "Stainless Moving Console (Pantograph)", "62437",
      "უჟანგავი ლითონის მოძრავი კონსოლი (პანტოგრაფი).", "Stainless-steel moving console (pantograph).", "უჟანგავი ლითონი", "Stainless steel", IMG + "eq-spr-33.webp"),
    eq("spare", "eq-spr-console-adj", "უჟანგავი ლითონის მოძრავი რეგულირებადი კონსოლი", "Stainless Adjustable Moving Console", "TA0601-S",
      "უჟანგავი ლითონის მოძრავი რეგულირებადი კონსოლი.", "Stainless-steel adjustable moving console.", "უჟანგავი ლითონი", "Stainless steel", IMG + "eq-spr-34.webp"),
    eq("spare", "eq-spr-console-curved", "უჟანგავი ლითონის მოხრილი მოძრავი კონსოლი", "Stainless Curved Moving Console", "TA0603-S",
      "უჟანგავი ლითონის მოხრილი მოძრავი კონსოლი.", "Stainless-steel curved moving console.", "უჟანგავი ლითონი", "Stainless steel", IMG + "eq-spr-35.webp"),
    eq("spare", "eq-spr-console-double", "უჟანგავი ლითონის ორხელიანი მოძრავი რეგულირებადი კონსოლი", "Stainless Double-Arm Adjustable Console", "TA0602-S",
      "უჟანგავი ლითონის ორხელიანი მოძრავი რეგულირებადი კონსოლი.", "Stainless-steel double-arm adjustable moving console.", "უჟანგავი ლითონი", "Stainless steel", IMG + "eq-spr-36.webp"),
    eq("spare", "eq-spr-nozzle", "ფრქვევანა NOZZLE", "Nozzle", "",
      "მაღალი წნევის სათადარიგო ფრქვევანა.", "High-pressure replacement nozzle.", "", "", IMG + "eq-spr-37.webp"),
    eq("spare", "eq-spr-foam-cylinder-pistol", "ქაფის ბალონის პისტოლეტი 60 სმ", "Foam Cylinder Pistol 60 cm", "FGG01-60",
      "ქაფის ბალონის პისტოლეტი, 60 სმ.", "Foam-cylinder pistol, 60 cm.", "60 სმ", "60 cm", IMG + "eq-spr-38.webp"),
    eq("spare", "eq-spr-foam-lance-330", "ქაფის ლულა 330 მმ", "Foam Lance 330 mm", "",
      "ქაფის ლულა, 330 მმ.", "Foam lance, 330 mm.", "330 მმ · გერმანია", "330 mm · Germany", IMG + "eq-spr-39.webp"),
    eq("spare", "eq-spr-foam-filter", "ქაფის ფილტრი (ტაბლეტი) 14×10", "Foam Filter (Tablet) 14×10", "60123",
      "უჟანგავი ფოლადის ქაფის ფილტრი (ტაბლეტი), 14×10.", "Stainless-steel foam filter (tablet), 14×10.", "უჟანგავი ფოლადი · იტალია", "Stainless steel · Italy", IMG + "eq-spr-40.webp"),
    eq("spare", "eq-spr-foam-generator", "ქაფის წარმომქმნელი - იხრახნება HP პისტოლეტზე", "Foam Generator - Screws onto HP Pistol", "61465",
      "ქაფის წარმომქმნელი, რომელიც იხრახნება მაღალი წნევის პისტოლეტზე.", "Foam generator that screws onto the high-pressure pistol.", "იტალია", "Italy", IMG + "eq-spr-41.webp"),
    eq("spare", "eq-spr-foam-fixator", "ქაფის წარმომქმნელის ფიქსატორი", "Foam Generator Fixator", "62407",
      "ფიქსატორი ქაფის წარმომქმნელისთვის.", "Fixator for the foam generator.", "იტალია", "Italy", IMG + "eq-spr-42.webp"),
    eq("spare", "eq-spr-underbody-1", "ქვედა რეცხვის მოწყობილობა", "Under-Body Wash Device", "TA04",
      "ავტომობილის ქვედა ნაწილის სარეცხი მოწყობილობა.", "Device for washing the underside of a car.", "", "", IMG + "eq-spr-43.webp"),
    eq("spare", "eq-spr-underbody-2", "ქვედა რეცხვის მოწყობილობა", "Under-Body Wash Device", "TA05",
      "ავტომობილის ქვედა ნაწილის სარეცხი მოწყობილობა.", "Device for washing the underside of a car.", "", "", IMG + "eq-spr-44.webp"),
    eq("spare", "eq-spr-inner-coupling-kew", "შიდა ქურო KEW უჟანგავი ლითონი", "Inner Coupling KEW Stainless", "00313",
      "შიდა ქურო KEW აპარატებისთვის, უჟანგავი ლითონი.", "Inner coupling for KEW units, stainless steel.", "იტალია", "Italy", IMG + "eq-spr-45.webp"),
    eq("spare", "eq-spr-hose-protector-2", "შლანგის გადაბმის დამცავი 2", "Hose Coupling Protector 2", "HBR02DN6",
      "შლანგის გადაბმის დამცავი.", "Hose-coupling protector.", "", "", IMG + "eq-spr-46.webp"),
    eq("spare", "eq-spr-hose-protector-3", "შლანგის გადაბმის დამცავი 3", "Hose Coupling Protector 3", "HBR03DN8",
      "შლანგის გადაბმის დამცავი.", "Hose-coupling protector.", "", "", IMG + "eq-spr-47.webp"),
    eq("spare", "eq-spr-hose-protector", "შლანგის გადაბმის დამცავი", "Hose Coupling Protector", "HBR01DN6",
      "შლანგის გადაბმის დამცავი.", "Hose-coupling protector.", "", "", IMG + "eq-spr-48.webp"),
    eq("spare", "eq-spr-bent-fitting", "შტუცერი მოხრილი 3/8 მმ", "Bent Fitting 3/8 mm", "64475",
      "მოხრილი შტუცერი, 3/8 მმ.", "Bent fitting, 3/8 mm.", "გერმანია", "Germany", IMG + "eq-spr-49.webp"),
    eq("spare", "eq-spr-water-lance-600", "წყლის ლულა 600 მმ - სწორი", "Water Lance 600 mm - Straight", "L0301",
      "წყლის ლულა, 600 მმ, სწორი.", "Water lance, 600 mm, straight.", "600 მმ", "600 mm", IMG + "eq-spr-50.webp"),
    eq("spare", "eq-spr-water-lance-bent", "წყლის ლულა მოხრილი 700 და 900 მმ", "Water Lance Bent 700 & 900 mm", "L0501",
      "წყლის ლულა, მოხრილი, 700 და 900 მმ.", "Water lance, bent, 700 and 900 mm.", "700 / 900 მმ", "700 / 900 mm", IMG + "eq-spr-51.webp"),
    eq("spare", "eq-spr-water-lance", "წყლის ლულა", "Water Lance", "",
      "სათადარიგო წყლის ლულა.", "Replacement water lance.", "", "", IMG + "eq-spr-52.webp"),
    eq("spare", "eq-spr-hydraulic-hose", "ჰიდრავლიკური ორშრიანი შლანგი 6 და 8 მმ", "Hydraulic Double-Layer Hose 6 & 8 mm", "62512",
      "ჰიდრავლიკური ორშრიანი შლანგი, 250 bar.", "Hydraulic double-layer hose, 250 bar.", "6 / 8 მმ · 250 bar", "6 / 8 mm · 250 bar", IMG + "eq-spr-54.webp"),
    eq("spare", "eq-spr-hydraulic-protector", "ჰიდრავლიკური შლანგის დამცავი 8 და 6 მმ", "Hydraulic Hose Protector 8 & 6 mm", "20065",
      "დამცავი ჰიდრავლიკური შლანგისთვის, 8 და 6 მმ.", "Protector for the hydraulic hose, 8 and 6 mm.", "8 / 6 მმ", "8 / 6 mm", IMG + "eq-spr-55.webp")
  ];

  window.ESG_PRODUCTS = (window.ESG_PRODUCTS || []).concat(EQUIPMENT);
})();
